#!/bin/bash
# Name: HF openai/gpt-oss-120b
# Description: Local HF snapshot via vLLM (FP4, 65.3 GB on disk)
# VRAM: 81
#
# Auto-generated by DGX Model Manager, then hand-corrected for gpt-oss MXFP4 on GB10.
# Source snapshot:
# /home/josh/.cache/huggingface/hub/models--openai--gpt-oss-120b/snapshots/b5c939de8f754692c1647ca79fbf85e8c1e70f8a
#
# ROOT CAUSE of the OpenWebUI token-soup / harmony "unexpected tokens remaining
# in message header" 500s (vLLM issue #37030):
#   Stock vllm/vllm-openai:v0.20.0 ships an SM121-broken Marlin MXFP4 kernel. On
#   GB10 (sm_121) it miscomputes the FIRST decode token after prefill — the final
#   hidden state comes out zero, so the logit vector is uniform (every token
#   logprob == -log(vocab) == -12.211). At temp 0 argmax picks token 0 ('!'); at
#   temp>0 it draws a random multilingual token. That one garbage token lands
#   exactly where harmony expects <|channel|>, desyncing the StreamableParser →
#   null content/reasoning and streaming 500s. Every request's first decode token
#   was corrupt; tokens 2..N were healthy, which is why raw completions "looked"
#   coherent (one stray leading char) and greedy/short chat only sometimes broke.
#   NO env var / flag fixes this on 0.20.0 — the kernel binary itself is wrong
#   (--enforce-eager, disabling chunked-prefill, and VLLM_MARLIN_USE_ATOMIC_ADD=1
#   were all tried and did NOT help). The earlier "fp8 KV was the culprit" and
#   "Marlin verified correct" notes were WRONG.
#
# FIX: run the SM121-patched community image eugr/spark-vllm:latest (vLLM 0.23.1,
#   the eugr DGX-Spark build). Its Marlin kernel computes tok0 correctly
#   (' Paris' @ -1.23 for "The capital of France is", not the -12.211 uniform).
#   Verified: 8/8 temp-1.0 streaming generations clean, coherent chat content.
#   Its entrypoint is nvidia_entrypoint.sh (not `vllm serve`), so we pass the
#   full `vllm serve ...` command explicitly.
#
# Other settings (unchanged, still correct):
#   - --generation-config vllm: 'auto' (model's generation_config.json) breaks
#     harmony channel termination (content null). Keep 'vllm'.
#   - --moe-backend marlin + VLLM_MARLIN_USE_ATOMIC_ADD=1: only viable MXFP4 MoE
#     path on sm_121 (native TRTLLM/CUTLASS gate on capability-family 100; sm_121
#     is 120). atomic-add avoids a Marlin split-K race on SM121. Kept to match the
#     known-good eugr/muninn config.
#   - --max-model-len 65536: full-precision KV, ~324K token KV capacity, no OOM.
#   - No --kv-cache-dtype fp8 (not needed; memory is fine on the 128 GB pool).
#
# TIKTOKEN_ENCODINGS_BASE: offline safety for openai_harmony's o200k vocab — the
# container can't reach the openai blob CDN, so we host-seed o200k_base.tiktoken
# into the mounted HF cache (~/.cache/huggingface/harmony-encodings/) and point
# harmony at it. (Verified the loaded encoding returns the canonical special-token
# IDs: <|start|>=200006, <|channel|>=200005, <|end|>=200007, <|return|>=200002.)
set -euo pipefail

docker rm -f vllm_node 2>/dev/null || true

exec docker run --name vllm_node --restart unless-stopped --gpus all -p 8000:8000 \
  -v "$HOME/.cache/huggingface:/root/.cache/huggingface" \
  -e HF_HUB_OFFLINE=1 \
  -e CUDA_DEVICE_MAX_CONNECTIONS=8 \
  -e TIKTOKEN_ENCODINGS_BASE=/root/.cache/huggingface/harmony-encodings \
  -e VLLM_FLASHINFER_ALLREDUCE_BACKEND=trtllm \
  -e VLLM_USE_FLASHINFER_MOE_FP4=0 \
  -e VLLM_MARLIN_USE_ATOMIC_ADD=1 \
  eugr/spark-vllm:latest \
  vllm serve \
  --model "/root/.cache/huggingface/hub/models--openai--gpt-oss-120b/snapshots/b5c939de8f754692c1647ca79fbf85e8c1e70f8a" \
  --served-model-name "openai/gpt-oss-120b" "openai--gpt-oss-120b" vllm-active \
  --host 0.0.0.0 --port 8000 \
  --trust-remote-code --dtype auto \
  --gpu-memory-utilization 0.75 \
  --max-model-len 65536 --max-num-seqs 2 \
  --enable-chunked-prefill \
  --moe-backend marlin \
  --generation-config vllm
